name: ponto_geral
on:
  schedule: [{ cron: "0 9,11 * * *" }]  # 06:00 e 08:00 America/Sao_Paulo (UTC-3)
  workflow_dispatch:
env:
  TZ: America/Sao_Paulo
  PYTHONUNBUFFERED: "1"
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: criar credenciais.json
        shell: bash
        run: |
          printf '%s' "${{ secrets.GOOGLE_CREDENTIALS }}" > credenciais.json
          python - <<'PY'
import json; json.load(open('credenciais.json','r',encoding='utf-8')); print("✅ credenciais.json OK")
PY
      - run: pip install -r requirements.txt
      - run: python ponto_geral.py
